//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobMentality.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class MobSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MobSettings defaultInstance = ((MobSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MobSettings())));
        
        public static MobSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int TurnMinutes {
            get {
                return ((int)(this["TurnMinutes"]));
            }
            set {
                this["TurnMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int BreakMinutes {
            get {
                return ((int)(this["BreakMinutes"]));
            }
            set {
                this["BreakMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int TurnsTillBreak {
            get {
                return ((int)(this["TurnsTillBreak"]));
            }
            set {
                this["TurnsTillBreak"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ActivePeople {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ActivePeople"]));
            }
            set {
                this["ActivePeople"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection InactivePeople {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["InactivePeople"]));
            }
            set {
                this["InactivePeople"] = value;
            }
        }
    }
}
